### ISSUE TITLE
Update python version in dependencies

### ISSUE THREAD

**Issue by gammapopolam** [amauryval/OsmRx#11]
Currently when trying to install via pip it requires to have a python 3.11.0 version. Tested locally on 3.12.3 and it works well

**Comment by amauryval** [comment]
https://github.com/amauryval/OsmRx/pull/13

**Comment by amauryval** [comment]
Few things are needed to support the 3.13 python version. I will do it later ;). For now, the package will be available on the latest python 3.12.8 version. thank you for you feedback and suggestions !

**Comment by gammapopolam** [comment]
Thanks. Also it would be nice if you could upgrade rustworkx to 0.15.1

**Comment by amauryval** [comment]
I'm working on it, Hope it will good today ;)
